package event;

public class Type {

	public static enum Effect {
		METADE, DOBRO, ANULA, COMUM
	}

	public static enum ElemType {
		NORMAL, FIRE, WATER, ELETRIC, GRASS, ICE, FIGHTING, POISON, GROUND, FLYING, PSYCHIC, BUG, ROCK, GHOST, DRAGON
	}

	static Effect chart[][] = new Effect[15][15];

	public static void loadChart() {
		chart[ElemType.NORMAL.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.GRASS.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.NORMAL.ordinal()][ElemType.ROCK.ordinal()] = Effect.METADE;
		chart[ElemType.NORMAL.ordinal()][ElemType.GHOST.ordinal()] = Effect.ANULA;
		chart[ElemType.NORMAL.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.FIRE.ordinal()] = Effect.METADE;
		chart[ElemType.FIRE.ordinal()][ElemType.WATER.ordinal()] = Effect.METADE;
		chart[ElemType.FIRE.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.GRASS.ordinal()] = Effect.DOBRO;
		chart[ElemType.FIRE.ordinal()][ElemType.ICE.ordinal()] = Effect.DOBRO;
		chart[ElemType.FIRE.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.BUG.ordinal()] = Effect.DOBRO;
		chart[ElemType.FIRE.ordinal()][ElemType.ROCK.ordinal()] = Effect.METADE;
		chart[ElemType.FIRE.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.FIRE.ordinal()][ElemType.DRAGON.ordinal()] = Effect.METADE;
		chart[ElemType.WATER.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.FIRE.ordinal()] = Effect.DOBRO;
		chart[ElemType.WATER.ordinal()][ElemType.WATER.ordinal()] = Effect.METADE;
		chart[ElemType.WATER.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.GRASS.ordinal()] = Effect.METADE;
		chart[ElemType.WATER.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.GROUND.ordinal()] = Effect.DOBRO;
		chart[ElemType.WATER.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.ROCK.ordinal()] = Effect.METADE;
		chart[ElemType.WATER.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.WATER.ordinal()][ElemType.DRAGON.ordinal()] = Effect.METADE;
		chart[ElemType.ELETRIC.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.WATER.ordinal()] = Effect.DOBRO;
		chart[ElemType.ELETRIC.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.METADE;
		chart[ElemType.ELETRIC.ordinal()][ElemType.GRASS.ordinal()] = Effect.METADE;
		chart[ElemType.ELETRIC.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.GROUND.ordinal()] = Effect.ANULA;
		chart[ElemType.ELETRIC.ordinal()][ElemType.FLYING.ordinal()] = Effect.DOBRO;
		chart[ElemType.ELETRIC.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.ELETRIC.ordinal()][ElemType.DRAGON.ordinal()] = Effect.METADE;
		chart[ElemType.GRASS.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.GRASS.ordinal()][ElemType.FIRE.ordinal()] = Effect.METADE;
		chart[ElemType.GRASS.ordinal()][ElemType.WATER.ordinal()] = Effect.DOBRO;
		chart[ElemType.GRASS.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.GRASS.ordinal()][ElemType.GRASS.ordinal()] = Effect.METADE;
		chart[ElemType.GRASS.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.GRASS.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.GRASS.ordinal()][ElemType.POISON.ordinal()] = Effect.METADE;
		chart[ElemType.GRASS.ordinal()][ElemType.GROUND.ordinal()] = Effect.ANULA;
		chart[ElemType.GRASS.ordinal()][ElemType.FLYING.ordinal()] = Effect.METADE;
		chart[ElemType.GRASS.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.GRASS.ordinal()][ElemType.BUG.ordinal()] = Effect.METADE;
		chart[ElemType.GRASS.ordinal()][ElemType.ROCK.ordinal()] = Effect.DOBRO;
		chart[ElemType.GRASS.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.GRASS.ordinal()][ElemType.DRAGON.ordinal()] = Effect.METADE;
		chart[ElemType.ICE.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.WATER.ordinal()] = Effect.METADE;
		chart[ElemType.ICE.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.GRASS.ordinal()] = Effect.DOBRO;
		chart[ElemType.ICE.ordinal()][ElemType.ICE.ordinal()] = Effect.METADE;
		chart[ElemType.ICE.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.GROUND.ordinal()] = Effect.DOBRO;
		chart[ElemType.ICE.ordinal()][ElemType.FLYING.ordinal()] = Effect.DOBRO;
		chart[ElemType.ICE.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.ICE.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.NORMAL.ordinal()] = Effect.DOBRO;
		chart[ElemType.FIGHTING.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.GRASS.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.ICE.ordinal()] = Effect.DOBRO;
		chart[ElemType.FIGHTING.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.POISON.ordinal()] = Effect.METADE;
		chart[ElemType.FIGHTING.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.FIGHTING.ordinal()][ElemType.FLYING.ordinal()] = Effect.METADE;
		chart[ElemType.FIGHTING.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.METADE;
		chart[ElemType.FIGHTING.ordinal()][ElemType.BUG.ordinal()] = Effect.METADE;
		chart[ElemType.FIGHTING.ordinal()][ElemType.ROCK.ordinal()] = Effect.DOBRO;
		chart[ElemType.FIGHTING.ordinal()][ElemType.GHOST.ordinal()] = Effect.ANULA;
		chart[ElemType.FIGHTING.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.GRASS.ordinal()] = Effect.DOBRO;
		chart[ElemType.POISON.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.POISON.ordinal()] = Effect.METADE;
		chart[ElemType.POISON.ordinal()][ElemType.GROUND.ordinal()] = Effect.METADE;
		chart[ElemType.POISON.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.POISON.ordinal()][ElemType.BUG.ordinal()] = Effect.DOBRO;
		chart[ElemType.POISON.ordinal()][ElemType.ROCK.ordinal()] = Effect.METADE;
		chart[ElemType.POISON.ordinal()][ElemType.GHOST.ordinal()] = Effect.METADE;
		chart[ElemType.POISON.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.FIRE.ordinal()] = Effect.DOBRO;
		chart[ElemType.GROUND.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.DOBRO;
		chart[ElemType.GROUND.ordinal()][ElemType.GRASS.ordinal()] = Effect.METADE;
		chart[ElemType.GROUND.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.POISON.ordinal()] = Effect.DOBRO;
		chart[ElemType.GROUND.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.FLYING.ordinal()] = Effect.ANULA;
		chart[ElemType.GROUND.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.ROCK.ordinal()] = Effect.DOBRO;
		chart[ElemType.GROUND.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.GROUND.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.METADE;
		chart[ElemType.FLYING.ordinal()][ElemType.GRASS.ordinal()] = Effect.DOBRO;
		chart[ElemType.FLYING.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.DOBRO;
		chart[ElemType.FLYING.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.BUG.ordinal()] = Effect.DOBRO;
		chart[ElemType.FLYING.ordinal()][ElemType.ROCK.ordinal()] = Effect.METADE;
		chart[ElemType.FLYING.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.FLYING.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.DOBRO;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.POISON.ordinal()] = Effect.DOBRO;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.METADE;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.PSYCHIC.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.FIRE.ordinal()] = Effect.METADE;
		chart[ElemType.BUG.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.GRASS.ordinal()] = Effect.DOBRO;
		chart[ElemType.BUG.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.METADE;
		chart[ElemType.BUG.ordinal()][ElemType.POISON.ordinal()] = Effect.DOBRO;
		chart[ElemType.BUG.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.FLYING.ordinal()] = Effect.METADE;
		chart[ElemType.BUG.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.DOBRO;
		chart[ElemType.BUG.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.BUG.ordinal()][ElemType.GHOST.ordinal()] = Effect.METADE;
		chart[ElemType.BUG.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.FIRE.ordinal()] = Effect.DOBRO;
		chart[ElemType.ROCK.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.GRASS.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.ICE.ordinal()] = Effect.DOBRO;
		chart[ElemType.ROCK.ordinal()][ElemType.ROCK.ordinal()] = Effect.METADE;
		chart[ElemType.ROCK.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.GROUND.ordinal()] = Effect.METADE;
		chart[ElemType.ROCK.ordinal()][ElemType.FLYING.ordinal()] = Effect.DOBRO;
		chart[ElemType.ROCK.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.BUG.ordinal()] = Effect.DOBRO;
		chart[ElemType.ROCK.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.ROCK.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.NORMAL.ordinal()] = Effect.ANULA;
		chart[ElemType.GHOST.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.GRASS.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.ANULA;
		chart[ElemType.GHOST.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.GHOST.ordinal()][ElemType.GHOST.ordinal()] = Effect.DOBRO;
		chart[ElemType.GHOST.ordinal()][ElemType.DRAGON.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.NORMAL.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.FIRE.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.WATER.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.ELETRIC.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.GRASS.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.ICE.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.FIGHTING.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.POISON.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.GROUND.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.FLYING.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.PSYCHIC.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.BUG.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.ROCK.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.GHOST.ordinal()] = Effect.COMUM;
		chart[ElemType.DRAGON.ordinal()][ElemType.DRAGON.ordinal()] = Effect.DOBRO;
	}
	
	public static double getAlpha(ElemType a, ElemType b) {
		Effect effect = chart[a.ordinal()][b.ordinal()];
		
		switch (effect) {
		case DOBRO: return 2.0;
		case ANULA: return 0.0;
		case METADE: return 0.5;
		default: return 1.0;
		}
	}
}
